version: '2.4'
services:
  master:
    container_name: master
    restart: always
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - env/master.env
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:10
    container_name: database
    restart: always
    ports:
      - 5430:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - env/database.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5