version: '3'
services:
  master:
    container_name: master
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - env/master.env
    depends_on:
      - database
  database:
    image: postgres:10
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - env/database.env

