"""Укорочение id в БД

Revision ID: 035f04ae3366
Revises: f46db4fd4302
Create Date: 2021-06-23 12:27:05.977790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f04ae3366'
down_revision = 'f46db4fd4302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('completed_orders_courier_id_fkey', 'completed_orders', type_='foreignkey')
    op.drop_column('completed_orders', 'courier_id')
    op.drop_constraint('courier_assign_time_courier_id_fkey', 'courier_assign_time', type_='foreignkey')
    op.drop_column('courier_assign_time', 'courier_id')
    op.drop_constraint('order_courier_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'courier_id')
    op.drop_constraint('order_assign_time_order_id_fkey', 'order_assign_time', type_='foreignkey')
    op.drop_column('order_assign_time', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_assign_time', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_assign_time_order_id_fkey', 'order_assign_time', 'order', ['order_id'], ['order_id'])
    op.add_column('order', sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_courier_id_fkey', 'order', 'courier', ['courier_id'], ['courier_id'])
    op.add_column('courier_assign_time', sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courier_assign_time_courier_id_fkey', 'courier_assign_time', 'courier', ['courier_id'], ['courier_id'])
    op.add_column('completed_orders', sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('completed_orders_courier_id_fkey', 'completed_orders', 'courier', ['courier_id'], ['courier_id'])
    # ### end Alembic commands ###
