"""Добавление поля последнего успешного заказа в таблицу к успешным заказам

Revision ID: 11316580c08d
Revises: a628c913dbd6
Create Date: 2021-03-22 01:01:16.744744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11316580c08d'
down_revision = 'a628c913dbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_order', sa.Column('last_complete_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_order', 'last_complete_time')
    # ### end Alembic commands ###
