"""Добавление поля время выполнения внутри курьера

Revision ID: 157c9606cded
Revises: d0a8a612aa55
Create Date: 2021-03-19 22:24:13.936384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157c9606cded'
down_revision = 'd0a8a612aa55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('complete_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'complete_time')
    # ### end Alembic commands ###
