"""Добавление текущего веса курьера

Revision ID: 1ccc3552d8c8
Revises: 940dafae9a62
Create Date: 2021-03-19 22:54:06.088666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccc3552d8c8'
down_revision = '940dafae9a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('current_weight', sa.Integer(), nullable=True))
    op.add_column('courier', sa.Column('max_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier', 'max_weight')
    op.drop_column('courier', 'current_weight')
    # ### end Alembic commands ###
