"""Обновлении таблицы успешных заказов

Revision ID: 1d213c402d10
Revises: de9fdb3b95c9
Create Date: 2021-03-24 22:51:53.974240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d213c402d10'
down_revision = 'de9fdb3b95c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_orders', sa.Column('general_complete_time', sa.DateTime(), nullable=True))
    op.add_column('completed_orders', sa.Column('region', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_orders', 'region')
    op.drop_column('completed_orders', 'general_complete_time')
    # ### end Alembic commands ###
