"""Добавление связи заказ-курьер

Revision ID: 27bc5ecbd52d
Revises: 4946c82e76ec
Create Date: 2021-03-18 09:45:53.128066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bc5ecbd52d'
down_revision = '4946c82e76ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'courier', ['courier_id'], ['courier_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'courier_id')
    # ### end Alembic commands ###
