"""Добавление поля последний заказ в выполненных заказов

Revision ID: 33b25f37b9a5
Revises: 517d4de5acd8
Create Date: 2021-03-24 18:22:25.025266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b25f37b9a5'
down_revision = '517d4de5acd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_order', sa.Column('last_order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'completed_order', 'order', ['last_order'], ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completed_order', type_='foreignkey')
    op.drop_column('completed_order', 'last_order')
    # ### end Alembic commands ###
