"""Разбиение времени в БД заказов

Revision ID: 3a33a41a19a0
Revises: 27bc5ecbd52d
Create Date: 2021-03-19 14:25:17.882644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a33a41a19a0'
down_revision = '27bc5ecbd52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('assign_time_end', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('time_finish_hour', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('time_finish_min', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('time_start_hour', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('time_start_min', sa.Integer(), nullable=True))
    op.drop_column('order', 'is_assign')
    op.drop_column('order', 'delivery_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_hours', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('is_assign', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('order', 'time_start_min')
    op.drop_column('order', 'time_start_hour')
    op.drop_column('order', 'time_finish_min')
    op.drop_column('order', 'time_finish_hour')
    op.drop_column('order', 'assign_time_end')
    # ### end Alembic commands ###
