"""Добавление флагов внутри заказов

Revision ID: 4946c82e76ec
Revises: 052b186c3856
Create Date: 2021-03-18 09:45:23.444327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4946c82e76ec'
down_revision = '052b186c3856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courier', ['courier_id'])
    op.add_column('order', sa.Column('is_assign', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_complete')
    op.drop_column('order', 'is_assign')
    op.drop_constraint(None, 'courier', type_='unique')
    # ### end Alembic commands ###
