"""Добавление времени назначения в заказ

Revision ID: 517d4de5acd8
Revises: baec42cb43cc
Create Date: 2021-03-22 00:27:46.037604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517d4de5acd8'
down_revision = 'baec42cb43cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('assign_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'assign_time')
    # ### end Alembic commands ###
