"""Добавление таблицы для времени курьера

Revision ID: 57493e0f6da1
Revises: 3a33a41a19a0
Create Date: 2021-03-19 14:32:30.111030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57493e0f6da1'
down_revision = '3a33a41a19a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier', 'working_hours')
    op.drop_column('order', 'assign_time_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('assign_time_end', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('courier', sa.Column('working_hours', postgresql.ARRAY(sa.VARCHAR(length=30)), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
