"""Переименование поля в таблице выполненных заказов

Revision ID: 6b0f5b462a8b
Revises: 33b25f37b9a5
Create Date: 2021-03-24 18:24:33.107663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0f5b462a8b'
down_revision = '33b25f37b9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_order', sa.Column('last_order_id', sa.Integer(), nullable=True))
    op.drop_constraint('completed_order_last_order_fkey', 'completed_order', type_='foreignkey')
    op.create_foreign_key(None, 'completed_order', 'order', ['last_order_id'], ['order_id'])
    op.drop_column('completed_order', 'last_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_order', sa.Column('last_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'completed_order', type_='foreignkey')
    op.create_foreign_key('completed_order_last_order_fkey', 'completed_order', 'order', ['last_order'], ['order_id'])
    op.drop_column('completed_order', 'last_order_id')
    # ### end Alembic commands ###
