"""Укорочение id в БД3

Revision ID: 8a71156a212a
Revises: 59f9560d395e
Create Date: 2021-06-23 12:28:35.137189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a71156a212a'
down_revision = '59f9560d395e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'completed_orders', 'courier', ['courier_id'], ['id'])
    op.add_column('courier_assign_time', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courier_assign_time', 'courier', ['courier_id'], ['id'])
    op.add_column('order', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'courier', ['courier_id'], ['id'])
    op.add_column('order_assign_time', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_assign_time', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_assign_time', type_='foreignkey')
    op.drop_column('order_assign_time', 'order_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'courier_id')
    op.drop_constraint(None, 'courier_assign_time', type_='foreignkey')
    op.drop_column('courier_assign_time', 'courier_id')
    op.drop_constraint(None, 'completed_orders', type_='foreignkey')
    op.drop_column('completed_orders', 'courier_id')
    # ### end Alembic commands ###
