"""Добавление связи между заказам и таблицы с временем заказов

Revision ID: 940dafae9a62
Revises: 82e629e61ca9
Create Date: 2021-03-19 22:46:19.052728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940dafae9a62'
down_revision = '82e629e61ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_assign_time', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_assign_time', 'order', ['order_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_assign_time', type_='foreignkey')
    op.drop_column('order_assign_time', 'order_id')
    # ### end Alembic commands ###
