"""Создание связи курьера и времени его работы

Revision ID: d0a8a612aa55
Revises: 57493e0f6da1
Create Date: 2021-03-19 14:34:45.179351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a8a612aa55'
down_revision = '57493e0f6da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_assign_time',
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_start_hour', sa.Integer(), nullable=True),
    sa.Column('time_start_min', sa.Integer(), nullable=True),
    sa.Column('time_finish_hour', sa.Integer(), nullable=True),
    sa.Column('time_finish_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier_assign_time')
    # ### end Alembic commands ###
