"""Переименование таблицы

Revision ID: de9fdb3b95c9
Revises: 11316580c08d
Create Date: 2021-03-24 22:35:46.072275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de9fdb3b95c9'
down_revision = '11316580c08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('completed_orders', sa.Integer(), nullable=True),
    sa.Column('min_time', sa.Float(), nullable=True),
    sa.Column('last_complete_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('completed_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_order',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_complete_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], name='completed_order_courier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='completed_order_pkey')
    )
    op.drop_table('completed_orders')
    # ### end Alembic commands ###
