"""Изменение типа данных общего времени

Revision ID: f46db4fd4302
Revises: 1d213c402d10
Create Date: 2021-03-24 23:03:52.542682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f46db4fd4302'
down_revision = '1d213c402d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_orders', sa.Column('general_complete_seconds', sa.Integer(), nullable=True))
    op.drop_column('completed_orders', 'general_complete_time')
    op.drop_column('completed_orders', 'min_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_orders', sa.Column('min_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('completed_orders', sa.Column('general_complete_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('completed_orders', 'general_complete_seconds')
    # ### end Alembic commands ###
